[package]
name = "tempest"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
lazy-regex = "3.1.0"
strum = { version = "0.25", features = ["derive"] }
svg = "0.14.0"
